### ISSUE TITLE
How do I use this against a local directory?

### ISSUE THREAD

**Issue by marcscheuner-bfh** [aloneguid/stowage#10]
Library is great - documentation is .....spotty at best.....

I'm trying to use Stowage against a local directory for development, and Azure Blob container for production. But I can't even get the local disk part to work...

I have tried this code (and a great many variations of it - with or without trailing backslash, with or without file pattern, using full path in the .Of.LocalDisk() call or only when doing .Ls()) - so far, without any success:

```
using (IFileStorage fs = Files.Of.LocalDisk(@"D:\"))
{
    var entries = await fs.Ls(@"\projects\mailtemplates", false);
}
```

I keep getting this error:

>> ArgumentException: path needs to be a folder (Parameter 'path')

What am I doing wrong? I would like to get all the files (or preferably: all files matching a certain pattern) from this folder ....

**Comment by tcsaddul** [comment]
When you use the @ prefix, dont use double backslash.

**Comment by marcscheuner-bfh** [comment]
> When you use the @ prefix, dont use double backslash.

True - good point there. But even with just a single backslash - the error remains the same ....

**Comment by tcsaddul** [comment]
Try removing the \ after D: or before "projects"

**Comment by marcscheuner-bfh** [comment]
Tried removing "\" from "D:\", or the leading "\" from the path - or both - but none of that works - error stays the same

**Comment by tcsaddul** [comment]
Change backslash \ to slash /

**Comment by marcscheuner-bfh** [comment]
> Change backslash \ to slash /

Still the same ....

**Comment by aloneguid** [comment]
Folder ends with slash. You are trying to list a file hence your very first error.
