### ISSUE TITLE
Writing Azure blob larger than 10MiB fails with 400 Bad Request

### ISSUE THREAD

**Issue by zitmen** [aloneguid/stowage#11]
Hi,

I am writing large blobs to Azure blob storage and I keep getting response 400 Bad Request (The specified blob or block content is invalid). I tracked down the reason to a wrong block ID.
The documentation says (https://learn.microsoft.com/en-us/rest/api/storageservices/put-block?tabs=azure-ad):
> For a specified blob, all block IDs must be the same length. If a block is uploaded with a block ID of a different length than the block IDs for any existing uncommitted blocks, the service returns error response code 400 (Bad Request).

The stream write fails always on blob with ID 10, so once we don't get single digit ID, we are braking the requirement.
Since there is a limit of 50k blocks, I suggest to pad the ID to a 6 digit string.

Thanks,
Martin

**Comment by aloneguid** [comment]
Thanks for finding it and doing the PR, great work! I'll try to release this tomorrow.

**Comment by jmkinzer** [comment]
Thanks! This saved me some pain.
