### ISSUE TITLE
Can't use SAS tokens for Azure?

### ISSUE THREAD

**Issue by stevehansen** [aloneguid/stowage#21]
https://github.com/aloneguid/stowage/blob/92612a6d12c0f78c93d38b65f3bb280bc07f6f1a/src/Stowage/Impl/Microsoft/SasAuthHandler.cs#L8C11-L8C26

The implementation seems to exist but I can't find any place that actually uses that class, and since it is all internal I can't call it myself either?

**Comment by aloneguid** [comment]
Oh i see. The work has started but never finished a while ago (hence the class is internal).

**Comment by stevehansen** [comment]
@aloneguid I see, it doesn't really do anything 😄  you want me to make a PR for it?

**Comment by aloneguid** [comment]
Yes please, that would be awesome!
